apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app
spec:
  selector:
    matchLabels:
      app: register-app
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
      - name: registerapp
        image: nidayra/githubactions-app:latest
        ports:
        - containerPort: 8080
