apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: register-app
  name: register-app
  namespace: default
spec: 
  ports: 
  - port: 80
    protocol: TCP
    targetPort: 80
  selector: 
    app: register-app
    type: NodePort
