name: Basics CICD pipeline - GitHub Hosted Runner
on: [workflow_dispatch]
jobs: 
  clean: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: clean job
        run: mvn clean  
  compile:
    runs-on: ubuntu-latest
    needs: clean
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: compile job
        run: mvn compile
  staticanalysis:
    needs: compile
    uses: NidaAP/maven-register-app/.github/workflows/sonarcloud-analysis.yml@main
    with: 
      projectKey: "NidaAP_maven-register-app"
      organization: "nidaap"
    secrets: 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  unittesting:
    runs-on: ubuntu-latest
    needs: staticanalysis
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: unit testing job
        run: mvn test
  build:
    runs-on: ubuntu-latest
    needs: unittesting
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build package job
        run: mvn package
