name: CI pipeline-demo
on: #trigger
  push:
    branches-ignore: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: view the project files
        run: ls -l
