name: Build and Push the Docker image
on: [workflow_dispatch]
jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: setup java
        uses: actions/setup-java@v4.7.0
        with: 
          distribution: 'temurin'
          java-version: '21'
      - name: maven build
        run: mvn clean compile package
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: | 
            nidayra/githubactions-app:latest
            nidayra/githubactions-app:${{ github.run_number }}
          context: .
  k8s:
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4.2.2
      - name: modify the deployment manifest with the current image
        run: |
          git config user.email smilykodi@gmail.com
          git config user.name NidaAP
          cd k8s
          cat deployment.yml
          sed -i "s+nidayra/githubactions-app.*+nidayra/githubactions-app:${{ github.run_number }}+g" deployment.yml
          cat deployment.yml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push
    
