name: 25-02-25 - Events workflow
on: 
  push: 
    branches: [main]
    branches-ignore: [user1]
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '*/2 * * * *'
 
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: just a execution
        run: echo "Hello"
      
