name: Java CI with Maven
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build with Maven
      run: mvn -B package --file pom.xml


